# Generated by Django 4.1.3 on 2022-12-05 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_install_place', models.CharField(max_length=100, verbose_name='สถานที่ติดตั้ง')),
                ('network_name', models.CharField(max_length=100, verbose_name='ชื่อเครือข่าย')),
                ('network_version', models.CharField(max_length=20, verbose_name='รุ่นของอุปกรณ์')),
                ('name_in_system', models.CharField(max_length=20, verbose_name='ชื่ออุปกรณในระบบ ')),
                ('mac_address', models.CharField(max_length=30, verbose_name='MAC Address')),
                ('ip_address', models.CharField(max_length=30, verbose_name='IP Address')),
                ('network_got', models.CharField(max_length=5, verbose_name='ที่มาของอุปกรณ์(โครงการ/หน่วยจัดหา/ส่วนตัว)')),
                ('serial_number', models.CharField(max_length=18, verbose_name='SERIAL NUMBER')),
                ('person_responsible', models.CharField(max_length=10, verbose_name='SERIAL NUMBER')),
                ('person_responsible_phone', models.CharField(max_length=10, verbose_name='จนท.ผู้รับผิดชอบ')),
                ('status_computer', models.CharField(choices=[('ใช้ราชการ', 'ใช้ราชการ'), ('ชำรุด', 'ชำรุด'), ('ส่งซ่อม', 'ส่งซ่อม'), ('เบิกเปลี่ยน', 'เบิกเปลี่ยน')], default='ใช้ราชการ', max_length=20, verbose_name='รุ่นของ CPU')),
                ('note', models.CharField(max_length=100, verbose_name=' หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to=settings.AUTH_USER_MODEL)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='team.team')),
            ],
        ),
    ]
