# Generated by Django 4.1.3 on 2022-12-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_network_status_computer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='ip_address',
            new_name='network_ip_address',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='mac_address',
            new_name='network_mac_address',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='note',
            new_name='network_note',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='person_responsible',
            new_name='network_person_responsible',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='person_responsible_phone',
            new_name='network_person_responsible_phone',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='serial_number',
            new_name='network_serial_number',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='status_network',
            new_name='network_status',
        ),
        migrations.RemoveField(
            model_name='network',
            name='name_in_system',
        ),
        migrations.AddField(
            model_name='network',
            name='network_brand',
            field=models.CharField(default=1, max_length=50, verbose_name='ยี่ห้ออุปกรณ์ ex. Cisco  ฯลฯ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='network_name_in_system',
            field=models.CharField(default=1, max_length=50, verbose_name='ชื่ออุปกรณในระบบ, Hostname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='network_type',
            field=models.CharField(default=1, max_length=20, verbose_name='ชนิดอุปกรณ์ Rounter Switch ฯลฯ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='network',
            name='network_name',
            field=models.CharField(max_length=100, verbose_name='ชื่ออุปกรณ์เครือข่าย'),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_version',
            field=models.CharField(max_length=20, verbose_name='รุ่นอุปกรณ์เครือข่าย'),
        ),
    ]
