# Generated by Django 4.1.3 on 2022-12-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_ip_address_network_network_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='network_version',
        ),
        migrations.AlterField(
            model_name='network',
            name='network_name',
            field=models.CharField(max_length=100, verbose_name='ชื่อ/รุ่นอุปกรณ์เครือข่าย'),
        ),
    ]
