# Generated by Django 4.1.3 on 2022-12-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_network_network_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_start_year',
            field=models.CharField(default=2563, max_length=4, verbose_name='เริมใช้อุปกรณ์เครือข่ายปี พ.ศ.'),
            preserve_default=False,
        ),
    ]
