# Generated by Django 4.1.3 on 2022-11-30 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10, verbose_name='ยศ')),
                ('first_name', models.CharField(max_length=50, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=50, verbose_name='นามสกุล')),
                ('position', models.CharField(max_length=100, verbose_name='ตำแหน่ง')),
                ('email_rtaf', models.EmailField(max_length=254, verbose_name='@rtaf')),
                ('email_public', models.EmailField(max_length=254, verbose_name='@gmail')),
                ('mobile', models.CharField(max_length=10, verbose_name='เบอร์โทรศัพท์เคลื่อนที่')),
                ('phone_rtaf', models.CharField(max_length=5, verbose_name='เบอร์โทรภายใน ทอ.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'In Active')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
