# Generated by Django 4.1.3 on 2022-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_alter_computer_computer_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='antivirus_copyright',
            field=models.CharField(max_length=5, verbose_name='ลิขสิทธิ์ของโปรแกรม'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='antivirus_name',
            field=models.CharField(max_length=50, verbose_name='ชื่อโปรแกรมป้องกันไวรัส'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_acquisition',
            field=models.CharField(max_length=50, verbose_name='คอมพิวเตอร์จากโครงการ'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_brand',
            field=models.CharField(max_length=10, verbose_name='ยี่ห้อของอุปกรณ์'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_mac_address',
            field=models.CharField(max_length=17, verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_number_rtaf',
            field=models.CharField(max_length=16, verbose_name='หมายเลขพัสดุ ทอ'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_start_use_year',
            field=models.CharField(max_length=4, verbose_name='เริ่ใใช้เครื่อง พ.ศ.?'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_use_network',
            field=models.CharField(max_length=20, verbose_name='เครื่องข่ายที่ใช้'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu_brand',
            field=models.CharField(max_length=10, verbose_name='ยี่ห้อของ CPU'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu_model',
            field=models.CharField(max_length=20, verbose_name='รุ่นของ CPU'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu_speed_clock',
            field=models.CharField(max_length=5, verbose_name='ความเร็วสัญญาณนาฬิกา'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu_unit_speed_clock',
            field=models.CharField(max_length=3, verbose_name='หน่วยความเร็วสัญญาณนาฬิกา'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk_capacity_1',
            field=models.CharField(max_length=5, verbose_name='ความจุของ Harddisk'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk_capacity_2',
            field=models.CharField(max_length=5, verbose_name='ความจุของ Harddisk'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk_unit_1',
            field=models.CharField(max_length=5, verbose_name='หน่วย Harddisk'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk_unit_2',
            field=models.CharField(max_length=5, verbose_name='หน่วย Harddisk'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='office_copyright',
            field=models.CharField(max_length=5, verbose_name='ลิขสิทธิ์ของโปรแกรมสำนักงาน'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='office_model_year',
            field=models.CharField(max_length=4, verbose_name='รุ่นโปรแกรม'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='office_name',
            field=models.CharField(max_length=50, verbose_name='ชื่อโปรแกรมสำนักงาน'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_computer',
            field=models.CharField(max_length=20, verbose_name='ชื่อระบบปฏิบัติการ'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_copyright',
            field=models.CharField(max_length=5, verbose_name='ลิขสิทธิ์ของระบบปฏิบัติการ'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='person_responsible',
            field=models.CharField(max_length=100, verbose_name='ผู้รับผิดชอบ'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram_capacity',
            field=models.CharField(max_length=3, verbose_name='ความจุ RAM'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram_type',
            field=models.CharField(max_length=5, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram_unit_capacity',
            field=models.CharField(max_length=3, verbose_name='หน่วย RAM'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status_computer',
            field=models.CharField(max_length=20, verbose_name='สถานภาพ Computer'),
        ),
    ]
