# Generated by Django 4.1.3 on 2022-12-07 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computer', '0003_alter_computer_antivirus_copyright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_start_use_year',
            field=models.CharField(max_length=4, verbose_name='เริ่มใช้เครื่อง พ.ศ.?'),
        ),
        migrations.CreateModel(
            name='Addupdatecomputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_install_place', models.CharField(max_length=100, verbose_name='สถานที่ติดตั้งอุปกรณ์')),
                ('computer_name', models.CharField(max_length=100, verbose_name='ชื่อเครื่องคอมพิวเตอร์')),
                ('cpu_brand', models.CharField(max_length=10, verbose_name='ยี่ห้อของ CPU')),
                ('cpu_model', models.CharField(max_length=20, verbose_name='รุ่นของ CPU')),
                ('cpu_speed_clock', models.CharField(max_length=5, verbose_name='ความเร็วสัญญาณนาฬิกา')),
                ('cpu_unit_speed_clock', models.CharField(max_length=3, verbose_name='หน่วยความเร็วสัญญาณนาฬิกา')),
                ('computer_use_network', models.CharField(max_length=20, verbose_name='เครื่องข่ายที่ใช้')),
                ('ram_type', models.CharField(max_length=5, verbose_name='RAM')),
                ('ram_capacity', models.CharField(max_length=3, verbose_name='ความจุ RAM')),
                ('ram_unit_capacity', models.CharField(max_length=3, verbose_name='หน่วย RAM')),
                ('harddisk_type_1', models.CharField(max_length=10, verbose_name='ประเภท Harddisk')),
                ('harddisk_capacity_1', models.CharField(max_length=5, verbose_name='ความจุของ Harddisk')),
                ('harddisk_unit_1', models.CharField(max_length=5, verbose_name='หน่วย Harddisk')),
                ('harddisk_type_2', models.CharField(max_length=10, verbose_name='ประเภท Harddisk')),
                ('harddisk_capacity_2', models.CharField(max_length=5, verbose_name='ความจุของ Harddisk')),
                ('harddisk_unit_2', models.CharField(max_length=5, verbose_name='หน่วย Harddisk')),
                ('os_computer', models.CharField(max_length=20, verbose_name='ชื่อระบบปฏิบัติการ')),
                ('os_copyright', models.CharField(max_length=5, verbose_name='ลิขสิทธิ์ของระบบปฏิบัติการ')),
                ('office_name', models.CharField(max_length=50, verbose_name='ชื่อโปรแกรมสำนักงาน')),
                ('office_model_year', models.CharField(max_length=4, verbose_name='รุ่นโปรแกรม')),
                ('office_copyright', models.CharField(max_length=5, verbose_name='ลิขสิทธิ์ของโปรแกรมสำนักงาน')),
                ('antivirus_name', models.CharField(max_length=50, verbose_name='ชื่อโปรแกรมป้องกันไวรัส')),
                ('antivirus_copyright', models.CharField(max_length=5, verbose_name='ลิขสิทธิ์ของโปรแกรม')),
                ('computer_start_use_year', models.CharField(max_length=4, verbose_name='เริ่มใช้เครื่อง พ.ศ.?')),
                ('person_responsible', models.CharField(max_length=100, verbose_name='ผู้รับผิดชอบ')),
                ('person_responsible_phone', models.CharField(max_length=10, verbose_name='ประเภท Harddisk')),
                ('status_computer', models.CharField(max_length=20, verbose_name='สถานภาพ Computer')),
                ('note', models.CharField(max_length=100, verbose_name=' หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addupdatecomputers', to='computer.computer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Addupdatecomputer', to=settings.AUTH_USER_MODEL)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addupdatecomputers', to='team.team')),
            ],
        ),
    ]
