# Generated by Django 4.1.3 on 2022-12-07 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computer', '0004_alter_computer_computer_start_use_year_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addupdatecomputer',
            new_name='Updatecomputer',
        ),
    ]
