# Generated by Django 4.1.3 on 2022-12-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('computer', '0006_upgradecomputer_delete_updatecomputer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.CharField(max_length=10, verbose_name='ประเภทอุปกรณ์คอมพิวเตอร์'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk_capacity_1',
            field=models.CharField(max_length=5, verbose_name='ความจุของ Harddisk Primary'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk_capacity_2',
            field=models.CharField(max_length=5, verbose_name='ความจุของ Harddisk Secondary'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk_type_1',
            field=models.CharField(max_length=10, verbose_name='ประเภท Harddisk '),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk_type_2',
            field=models.CharField(max_length=10, verbose_name='ประเภท Harddisk Primary'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk_unit_1',
            field=models.CharField(max_length=5, verbose_name='หน่วย Harddisk Primary'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='harddisk_unit_2',
            field=models.CharField(max_length=5, verbose_name='หน่วย Harddisk Secondary'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_computer',
            field=models.CharField(max_length=20, verbose_name='ชื่อระบบปฏิบัติการ Secondary'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='person_responsible_phone',
            field=models.CharField(max_length=10, verbose_name='เบอร์ติดต่อผู้รับผิดชอบ'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='team.team', verbose_name='กรม'),
        ),
    ]
